<?php

namespace App\Support;

final class ErrorCode
{
    public const AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

    public const AUTH_ACCOUNT_INACTIVE = 'AUTH_ACCOUNT_INACTIVE';

    public const AUTH_ACCOUNT_BANNED = 'AUTH_ACCOUNT_BANNED';

    public const AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED';

    public const AUTH_THROTTLED = 'AUTH_THROTTLED';

    public const AUTH_RESET_TOKEN_INVALID = 'AUTH_RESET_TOKEN_INVALID';

    public const AUTH_FORBIDDEN = 'AUTH_FORBIDDEN';

    public const VALIDATION_FAILED = 'VALIDATION_FAILED';

    public const CSRF_TOKEN_MISMATCH = 'CSRF_TOKEN_MISMATCH';

    public const CATALOG_SLUG_TAKEN = 'CATALOG_SLUG_TAKEN';

    public const CATALOG_SKU_TAKEN = 'CATALOG_SKU_TAKEN';

    public const CATALOG_VARIANT_INVARIANT = 'CATALOG_VARIANT_INVARIANT';

    public const CATALOG_CATEGORY_CYCLE = 'CATALOG_CATEGORY_CYCLE';

    public const CATALOG_RESOURCE_IN_USE = 'CATALOG_RESOURCE_IN_USE';

    public const CATALOG_NOT_FOUND = 'CATALOG_NOT_FOUND';

    public const INVENTORY_NOT_FOUND = 'INVENTORY_NOT_FOUND';

    public const INVENTORY_INSUFFICIENT_STOCK = 'INVENTORY_INSUFFICIENT_STOCK';

    public const CART_NOT_FOUND = 'CART_NOT_FOUND';

    public const CART_INVALID_TOKEN = 'CART_INVALID_TOKEN';

    public const CHECKOUT_INVALID_CART = 'CHECKOUT_INVALID_CART';

    public const ORDER_INVALID_TRANSITION = 'ORDER_INVALID_TRANSITION';

    public const COUPON_INVALID = 'COUPON_INVALID';

    public const PAYMENT_METHOD_INVALID = 'PAYMENT_METHOD_INVALID';

    public const PAYMENT_INVALID_SIGNATURE = 'PAYMENT_INVALID_SIGNATURE';

    public const PAYMENT_ALREADY_SETTLED = 'PAYMENT_ALREADY_SETTLED';

    public const SHIPMENT_INVALID_STATUS = 'SHIPMENT_INVALID_STATUS';

    public const SHIPMENT_TRACKING_REQUIRED = 'SHIPMENT_TRACKING_REQUIRED';

    public const SHIPMENT_ALREADY_EXISTS = 'SHIPMENT_ALREADY_EXISTS';
}
